# Generated by Django 4.2 on 2023-06-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='designation',
            field=models.CharField(default='Professor', max_length=30),
        ),
    ]
