# Generated by Django 4.2 on 2023-06-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_professor_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('day', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_routine', to='dashboard.course')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_stream', to='dashboard.stream')),
            ],
        ),
    ]
