# Generated by Django 4.2 on 2023-06-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default='10:00'),
        ),
    ]
