# Generated by Django 4.2 on 2023-06-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schedules/'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='semester', max_length=50),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
    ]
