# Generated by Django 4.2 on 2023-04-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_stream_delete_specialisation_student_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
