# Generated by Django 4.2 on 2023-04-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_streams_student_stream'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Streams',
            new_name='Stream',
        ),
    ]
