# Generated by Django 4.2 on 2023-04-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_streams_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='dashboard.course'),
        ),
    ]
