# Generated by Django 4.2 on 2023-04-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_stream_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='dashboard.course'),
        ),
    ]
