# Generated by Django 4.2 on 2023-04-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_stream_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='courses',
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(max_length=1),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(max_length=1)),
                ('courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='dashboard.course')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_chosen', to='dashboard.stream')),
            ],
        ),
    ]
