# Generated by Django 4.2 on 2023-04-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_semester_semester_alter_student_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
