# Generated by Django 4.2 on 2023-04-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_delete_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='professor_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_pics/'),
        ),
    ]
