# Generated by Django 4.2 on 2023-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_professor_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
