# Generated by Django 4.2 on 2023-05-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_map'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Maps',
        ),
    ]
