# Generated by Django 4.2 on 2023-06-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_rename_map_maps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maps',
        ),
    ]
